version: "3.2"
networks:
  web:
    external: true
  backend:
services:
  php:
    container_name: ${container_prefix}_php
    image: mbamber1986/php
    networks:
      - backend
    restart: always
    working_dir: ${workdir}
    volumes:
      - ./www/:${workdir}
  apache:
    container_name: ${container_prefix}_apache
    image: mbamber1986/apache
    working_dir: ${workdir}
    environment:
      - workdir=${workdir}
      - web_root=${web_root}
    depends_on:
      - php
      - mysql
    networks:
      - web
      - backend
    restart: always
    volumes:
      - ./www/:${workdir}
  mysql:
    container_name: ${container_prefix}_mysql
    image: mysql:5.6.40
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
  ngrok:
    image: shkoliar/ngrok:latest
    container_name: ${container_prefix}_ngrok
    links: 
      - apache
    ports:
      - 4551
    networks:
      - web
      - backend
    environment:
      - DOMAIN=apache
      - PORT=80
    restart: always