version: "3.2"
networks:
  web:
    external: true
  backend:
services:
  php:
    container_name: ${prefix}_php
    image: mbamber1986/php
    networks:
      - backend
    restart: always
    volumes:
      - ./public_html/:/var/www/html
  apache:
    container_name: ${prefix}_apache
    image: mbamber1986/apache
    # build:
    #   context: ./apache
    #   dockerfile: Dockerfile
    #   args:
    #     - workdir=${workdir}
    #     - web_root=${web_root}
    volumes:
      # - ./apache/vhost.conf:/usr/local/apache2/conf/vhosts.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${prefix}_web.rule=Host(`${domain}`)"
      - "traefik.http.routers.${prefix}_web.entrypoints=web"
      - "traefik.http.routers.${prefix}_websecure.rule=Host(`${domain}`)"
      - "traefik.http.routers.${prefix}_websecure.entrypoints=websecure"
      - "traefik.http.routers.${prefix}_websecure.tls.certresolver=myresolver"
      - "traefik.docker.network=web"

    environment:
      - workdir=${workdir}
      - web_root=${web_root}
    depends_on:
      - php
      - mysql
    networks:
      - web
      - backend
    restart: always
    volumes:
      - ./public_html/:/var/www/html
  mysql:
    container_name: ${prefix}_mysql
    image: mysql:5.6.40
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - backend
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword